const { PrismaClient, AccessTypes } = require('@prisma/client');
const prisma = new PrismaClient();
const bcrypt = require('bcryptjs');
const generateOtp = require('../otp/generateOTP');
const { sendMail } = require('../email/nodeMailer');
const loadTemplate = require('../email/loadTemplate');

const DEFAULT_VALUES = {
    name: "NA",
    access: AccessTypes.USER,
    year: "NA",
    img: "NA",
    rollNumber: "NA",
    school: "NA",
    college: "NA",
    contactNo: "NA",
    whatsappNo: "NA",
    forms: [],
    extra: {},
};

const createUser = async (data, override = {}, sendMailFlag = false) => {
    console.log(data, override, sendMailFlag);
    console.log("Creating new user");
    
    let password;
    let hashedPassword;
    let autoGeneratedPassword = false;

    if (override.password) {
        hashedPassword = override.password;
    } else if (data.password) {
        password = data.password;
        hashedPassword = await bcrypt.hash(password, 10);
    } else {
        console.log("Generating hashed password");
        password = generateOtp(7, true, true, true);
        hashedPassword = await bcrypt.hash(password, 10);
        autoGeneratedPassword = true;
    }

    console.log("hashedpassword", hashedPassword);

    try {
        const user = await prisma.user.create({
            data: {
                ...DEFAULT_VALUES,
                password: hashedPassword,
                ...data,
                ...override,
            },
        });

        console.log(`Created user with email ${data.email || override.email} and access ${override.access || data.access || DEFAULT_VALUES.access} successfully!`);

        if (sendMailFlag || autoGeneratedPassword) {
            const subject = 'Welcome to FED KIIT';
            let templateName, placeholders;
            if (autoGeneratedPassword) {
                // Send email with password to the new auto-generated user
                templateName = 'newUserAutoRegistration';
                placeholders = { password: password, name: user.name };
            } else {
                // Send email to the newly registered user
                templateName = "newUserRegistration";
                placeholders = { name: user.name };
            }

            const templateContent = loadTemplate(templateName, placeholders);
            console.log("Sending email to", user.email);
            sendMail(user.email, subject, templateContent);
        }

        return user;
    } catch (error) {
        console.error('Error creating user:', error);
        throw new Error('User creation failed');
    }
};

module.exports = createUser;
